### ISSUE TITLE
Is this still best way to install ROS on Tx1?

### ISSUE THREAD

**Issue by Russ76** [jetsonhacks/installGrinch#1]
Since this repo is two years old, is it still current? Or does the latest L4T version accomplish some of these updates?

**Comment by jetsonhacks** [comment]
installGrinch is not used on the TX1. Did you mean TK1 or TX1?

**Comment by Russ76** [comment]
Thanks for the answer! I apologize for getting the K and X mixed up. Updated L4T today and will load ROS into my X.
