### ISSUE TITLE
Can I use installGrinch on Tx1?

### ISSUE THREAD

**Issue by yang778** [jetsonhacks/installGrinch#2]
Hi, @jetsonhacks 
I'm working on Tx1 now and want to connect Tx1 to arduino board. But the problem is the Tx1 cannot take ownership of the arduino usb device. So, do you have an alternative of installGrinch for Tx1 or any advice?

Thank you in advance!

**Comment by jetsonhacks** [comment]
I have no alternative to the Grinch Kernel on the TX1. If it's a authentic Arduino, it uses a FTDI serial to USB converter and should work. Inexpensive clones may use a different chip, such as a 'USB Winchiphead CH341 Single Port Serial Driver' which requires a kernel module to be created and installed on the Jetson TX1.
